# Generated by Django 3.0.8 on 2022-07-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_rec', models.CharField(max_length=200)),
                ('fecha_rec', models.DateField()),
            ],
        ),
    ]
