# Generated by Django 3.0.8 on 2022-06-02 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_perfil', models.CharField(blank=True, max_length=10)),
                ('telefono_perfil', models.CharField(blank=True, max_length=10)),
                ('direccion_perfil', models.CharField(blank=True, max_length=80)),
                ('area_perfil', models.CharField(blank=True, max_length=80)),
                ('cargo_perfil', models.CharField(blank=True, max_length=80)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
