# Generated by Django 3.0.8 on 2022-06-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cargo_perfil',
            field=models.CharField(blank=True, choices=[('', ''), ('vendedor', 'Vendedor'), ('Tecnico-PC', 'Tecnico-PC'), ('Tecnico-AUD', 'Tecnico-AUD')], max_length=80),
        ),
    ]
