# Generated by Django 3.0.8 on 2022-06-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20220602_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cargo_perfil',
            field=models.CharField(blank=True, choices=[('vendedor', 'Vendedor'), ('Técnico-PC', 'Técnico-PC'), ('Técnico-AUD', 'Técnico-AUD')], max_length=80),
        ),
    ]
