# Generated by Django 3.0.8 on 2022-07-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='descripcion_pieza',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='nombre_pieza',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
