# Generated by Django 3.0.8 on 2022-06-12 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_man', models.CharField(blank=True, max_length=100, verbose_name='Código de Mantenimiento')),
                ('tipo_man', models.CharField(blank=True, choices=[('Ingresado', 'Ingresado'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado'), ('Entregado', 'Entregado')], max_length=200, verbose_name='Tipo de Mantenimiento')),
                ('estado_man', models.CharField(choices=[('Ingresado', 'Ingresado'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado'), ('Entregado', 'Entregado')], default='Ingresado', max_length=200, verbose_name='Estado de Mantenimiento')),
                ('fecha_ingreso_man', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('fecha_salida_man', models.DateTimeField(blank=True, verbose_name='Fecha de Salida')),
                ('fecha_entrega_man', models.DateTimeField(blank=True, verbose_name='Fecha de Entrega')),
                ('marca_equipo_man', models.CharField(blank=True, max_length=100, verbose_name='Marca del Equipo')),
                ('modelo_equipo_man', models.CharField(blank=True, max_length=100, verbose_name='Modelo del Equipo')),
                ('accesorios_equipo_man', models.TextField(blank=True, verbose_name='Accesorios del equipo')),
                ('falla_equipo_man', models.TextField(blank=True, verbose_name='Fallas del equipo')),
                ('procedimiento_man', models.TextField(blank=True, verbose_name='Procedimiento Realizado')),
                ('observaciones_man', models.TextField(blank=True, verbose_name='Oservaciones del Tecnico')),
                ('costo_man', models.FloatField(blank=True, verbose_name='Costo del Mantenimiento')),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
