# Generated by Django 3.0.8 on 2022-06-15 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20220602_2319'),
        ('mantenimiento', '0002_auto_20220614_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='usuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Perfil'),
        ),
    ]
