# Generated by Django 3.0.8 on 2022-06-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_auto_20220614_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='tipo_equipo_man',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de Equipo'),
        ),
    ]
