# Generated by Django 3.0.8 on 2022-06-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_mantenimiento_tipo_equipo_man'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_entrega_man',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_salida_man',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Salida'),
        ),
    ]
