# Generated by Django 3.0.8 on 2022-06-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0005_auto_20220615_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='costo_man',
            field=models.FloatField(blank=True, null=True, verbose_name='Costo del Mantenimiento'),
        ),
    ]
