# Generated by Django 3.0.8 on 2022-06-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0006_auto_20220615_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo_man',
            field=models.CharField(blank=True, choices=[('Tecnologico', 'Tecnologico'), ('Audiovisual', 'Audiovisual')], max_length=200, verbose_name='Tipo de Mantenimiento'),
        ),
    ]
